name: Continuous Integration
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      REPO_DIR: qss-qasm
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ${{ env.REPO_DIR }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install conan==1.59.0
      - name: Create Conan default profile
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Create build directory
        run: mkdir build
      - name: Conan install
        run: conan install --build=outdated -pr:h default -pr:b default ../${{ env.REPO_DIR }}
        working-directory: build
      - name: CMake generate
        run: cmake ../${{ env.REPO_DIR }} -DBUILD_STATIC_LIBS=OFF -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
        working-directory: build
      - name: Make all
        run: make -j8
        working-directory: build
      - name: Short run tests
        run: ../../${{ env.REPO_DIR }}/tests/short-run-tests.sh
        working-directory: build/bin
      - name: CTest
        run: ctest
        working-directory: build